create table if not exists public.users (
    id bigint generated by default as identity primary key,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
    id bigint generated by default as identity primary key,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.blogs (
    id bigint generated by default as identity primary key,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.users disable row level security;
alter table public.jobs disable row level security;
alter table public.blogs disable row level security;

grant usage on schema public to anon;
grant select, insert, update, delete on public.users to anon;
grant select, insert, update, delete on public.jobs to anon;
grant select, insert, update, delete on public.blogs to anon;

grant usage, select on sequence public.users_id_seq to anon;
grant usage, select on sequence public.jobs_id_seq to anon;
grant usage, select on sequence public.blogs_id_seq to anon;
